name: Node js cicd
on:
  # Trigger the workflow on push to main branch or manually via workflow_dispatch
    push:
        branches:
            - main
    workflow_dispatch:
jobs:

    build:
        name: Test node project
        runs-on: ubuntu-latest
        steps:
            - name: Check Out
              uses: actions/checkout@v4

            - name: docker login
              run: docker login -u ${{secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

            - name: build image
              run: docker build -t babai12/aws_backend .

            - name: push image 
              run: docker push babai12/aws_backend:latest

    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: pull image
          run: docker pull babai12/aws_backend:latest

        - name: delete old container
          run: docker rm -f node_container

        - name: run image
          run: docker run -d -p 3000:3000 --name=node_container -e URL='${{secrets.URL}}' babai12/aws_backend:latest
